// Code generated by a template
// Project: Remember
// https://github.com/yiyungent/Remember
// Author: yiyun <yiyungent@gmail.com>
// LastUpadteTime: 2020-07-06 10:34:32
using Domain.Entities;
using Repositories.Core;
using Repositories.Interface;

namespace Repositories.Implement
{
    public partial class Role_MenuRepository : BaseRepository<Role_Menu>, IRole_MenuRepository
    {
        private readonly RemDbContext _context;

        public Role_MenuRepository(RemDbContext context) : base(context)
        {
            this._context = context;
        }
    }
}
