// Code generated by a template
// Project: remember
// https://github.com/yiyungent/remember
// Author: yiyun <yiyungent@gmail.com>
// LastUpadteTime: 2020-08-10 12:36:07
using Domain.Entities;
using Services.Core;

namespace Services.Interface
{
    public partial interface IArticle_ParticipantService : IService<Article_Participant>
    { }
}
