// Code generated by a template
// Project: remember
// https://github.com/yiyungent/remember
// Author: yiyun <yiyungent@gmail.com>
// LastUpadteTime: 2020-07-06 10:38:21
using Domain.Entities;
using Services.Core;

namespace Services.Interface
{
    public partial interface ISys_MenuService : IService<Sys_Menu>
    { }
}
