// Code generated by a template
// Project: remember
// https://github.com/yiyungent/remember
// Author: yiyun <yiyungent@gmail.com>
// LastUpadteTime: 2020-08-10 12:36:29
using Domain.Entities;
using Repositories.Interface;
using Services.Core;
using Services.Interface;

namespace Services.Implement
{
    public partial class Article_CommentService : BaseService<Article_Comment>, IArticle_CommentService
    {
        private readonly IArticle_CommentRepository _repository;
        public Article_CommentService(IArticle_CommentRepository repository) : base(repository)
        {
            this._repository = repository;
        }
    }
}
