// Code generated by a template
// Project: remember
// https://github.com/yiyungent/remember
// Author: yiyun <yiyungent@gmail.com>
// LastUpadteTime: 2020-07-06 10:36:54
using Domain.Entities;
using Repositories.Interface;
using Services.Core;
using Services.Interface;

namespace Services.Implement
{
    public partial class Comment_DislikeService : BaseService<Comment_Dislike>, IComment_DislikeService
    {
        private readonly IComment_DislikeRepository _repository;
        public Comment_DislikeService(IComment_DislikeRepository repository) : base(repository)
        {
            this._repository = repository;
        }
    }
}
