// Code generated by a template
// Project: remember
// https://github.com/yiyungent/remember
// Author: yiyun <yiyungent@gmail.com>
// LastUpadteTime: 2020-08-10 12:36:29
using Domain.Entities;
using Repositories.Interface;
using Services.Core;
using Services.Interface;

namespace Services.Implement
{
    public partial class Role_FunctionService : BaseService<Role_Permission>, IRole_PermissionService
    {
        private readonly IRole_PermissionRepository _repository;
        public Role_FunctionService(IRole_PermissionRepository repository) : base(repository)
        {
            this._repository = repository;
        }
    }
}
