// Code generated by a template
// Project: remember
// https://github.com/yiyungent/remember
// Author: yiyun <yiyungent@gmail.com>
// LastUpadteTime: 2020-07-06 10:36:54
using Domain.Entities;
using Repositories.Interface;
using Services.Core;
using Services.Interface;

namespace Services.Implement
{
    public partial class Role_UserService : BaseService<Role_User>, IRole_UserService
    {
        private readonly IRole_UserRepository _repository;
        public Role_UserService(IRole_UserRepository repository) : base(repository)
        {
            this._repository = repository;
        }
    }
}
